### ISSUE TITLE
Import nekolika objednavek do pohody v jednom souboru.

### ISSUE THREAD

**Issue by danilke** [Masa331/pohoda#1]
Ahoj, mam otazku, ktera mozna vubec neni spojena s repo. 

Pracuju nad importem objednavek do pohody. Jsem nasel priklad na stormware: 
`https://www.stormware.cz/xml/samples/version_2/import/Objednavky/order_01_v2.0.xml` 
Otazka, jestli muzu nejak importovat v jednem souboru nekolik objednavek, jestli ano, jak ma vypadat ten XML ? Dekuji!

**Comment by Masa331** [comment]
Ahoj

zkousel jsi neco takovehleho:
```
<dat:dataPack id="ob001" ico="12345678" application="StwTest" version="2.0" note="Import Objednávky">
  <dat:dataPackItem id="OBJ001" version="2.0">
    <ord:order version="2.0">
    ...
    </ord:order>
  </dat:dataPackItem>

  <dat:dataPackItem id="OBJ001" version="2.0">
    <ord:order version="2.0">
    ...
    </ord:order>
  </dat:dataPackItem>
</dat:dataPack>
```

Jestli to ctu spravne tak tak by to melo byt dle https://www.stormware.cz/xml/schema/version_2/data.xsd. Ja bohuzel ale pristup do Pohody nemam, takze to vyzkouset primo nemuzu.

**Comment by danilke** [comment]
Diky, zkusim to 👍
