### ISSUE TITLE
Adding new element to invoiceSummary

### ISSUE THREAD

**Issue by lidutka** [Masa331/pohoda#9]
Hi, 

Would you consider adding one element to invoiceSummary - `typeCalculateVATInclusivePrice`? I think many people would benefit from this since 

> Od 1.10.2019 je možné na dokladu možné použít pouze nový typ výpočtu DPH shora. Typ výpočtu DPH shora na dokladu je možné v XML nastavit pomocí elemenetu `typeCalculateVATInclusivePrice`. https://www.stormware.cz/pohoda/xml/provyvojare/vypocetcastky/

**Comment by Masa331** [comment]
hi @lidutka i will look into it

**Comment by lidutka** [comment]
Thanks :)

**Comment by lidutka** [comment]
Is there any chance you would manage this issue this week?

**Comment by Masa331** [comment]
@lidutka I'v just released version 3.0.0 with newest Pohoda schemas. Please check it out and write me if it's ok. I don't have data to test it on really
